name: aegle-app
version: 0.1.0
github: wasabi315/aegle
license: BSD-3-Clause
author: Satoshi Takimoto
maintainer: wasabi.nvim.st@gmail.com
copyright: 2016 András Kovács, 2025 Satoshi Takimoto

data-files:
  - migration/*.sql
  - static/style.css
  - static/script.js

synopsis: Type-based library search for Agda
category: Language

description: Please see the README on GitHub at <https://github.com/wasabi315/aegle#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - Agda
  - bytestring
  - containers
  - deepseq
  - deriving-aeson
  - directory
  - filepath
  - filemanip
  - flat
  - foldl
  - generic-lens
  - hashable
  - haskeline
  - hasql
  - hasql-dynamic-statements
  - hasql-migration
  - hasql-pool
  - hasql-th
  - hasql-transaction
  - lucid
  - megaparsec
  - microlens-platform
  - mtl
  - named
  - nonempty-containers
  - opt-env-conf
  - parser-combinators
  - prettyprinter
  - prettyprinter-ansi-terminal
  - profunctors
  - repline
  - servant
  - servant-lucid
  - servant-server
  - streamly
  - text
  - time
  - unordered-containers
  - uri-encode
  - vector
  - wai
  - wai-extra
  - warp
  - witherable
  - yaml

language: GHC2021

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - CPP
  - DataKinds
  - DerivingVia
  - DeriveAnyClass
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - InstanceSigs
  - ImplicitParams
  - KindSignatures
  - LambdaCase
  - MultilineStrings
  - MultiParamTypeClasses
  - MultiWayIf
  - NoFieldSelectors
  - NoImplicitPrelude
  - OrPatterns
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedRecordDot
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - QualifiedDo
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - Strict
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing
  - -O2
  - -funbox-strict-fields
  - -optP-Wno-nonportable-include-path

flags:
  debug:
    description: turn on debug traces
    default: false
    manual: true
  dump:
    description: dump core
    default: false
    manual: true
  llvm:
    description: use llvm for codegen
    default: false
    manual: true

when:
  - condition: flag(debug)
    cpp-options:
      - -DDEBUG
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file
  - condition: flag(llvm)
    ghc-options:
      - -fllvm

library:
  source-dirs: src

executables:
  aegle:
    main: Main.hs
    source-dirs: app
    dependencies:
      - aegle-app
    when:
      - condition: flag(debug)
        then:
          ghc-options:
            - -threaded
        else:
          ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts= "-A64M -N"

tests:
  aegle-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - aegle-app
      - tasty
      - hedgehog
      - tasty-hedgehog
      - tasty-hunit
